spring:
  application:
    name: module6-security-identity
  datasource:
    url: jdbc:postgresql://localhost:5434/module6
    username: module6
    password: module6
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

module6:
  jwt:
    issuer: module6-app
    access-expiration-minutes: 15
    refresh-expiration-days: 7
    secret: change-this-very-long-secret-key-for-production-min-32-bytes
