import java.util.*;
import java.util.stream.*;

/**
 * Lesson 5.3 - Intro to NoSQL (MongoDB)
 *
 * Models the MongoDB document/collection API in plain Java.
 * In your real project:
 *   @Document(collection = "users")
 *   public class User { @Id String id; String name; List<String> tags; }
 *
 * KEY TERMS:
 *   document    - a JSON-like record stored in MongoDB.
 *   collection  - a group of documents (analogous to a SQL table).
 *   _id         - the primary key field (auto-generated by MongoDB).
 *   index       - speeds up queries on a field.
 *   aggregation - multi-stage pipeline for data transformation.
 *   embedded doc - a nested document within another document.
 */
public class AnswerApp {

    // Simulate a document as a Map (MongoDB stores BSON, shown here as JSON-like maps)
    static class Document {
        final String id;
        final Map<String, Object> data = new LinkedHashMap<>();

        Document(String id) { this.id = id; }
        Document put(String k, Object v) { data.put(k, v); return this; }
        Object   get(String k) { return data.get(k); }

        @Override public String toString() {
            String fields = data.entrySet().stream()
                .map(e -> "\"" + e.getKey() + "\": " + formatValue(e.getValue()))
                .collect(Collectors.joining(", "));
            return "{ \"_id\": \"" + id + "\", " + fields + " }";
        }
        private static String formatValue(Object v) {
            if (v instanceof String) return "\"" + v + "\"";
            return String.valueOf(v);
        }
    }

    static class Collection {
        private final Map<String, Document> store = new LinkedHashMap<>();

        void insertOne(Document d) { store.put(d.id, d); }

        Optional<Document> findById(String id) {
            return Optional.ofNullable(store.get(id));
        }

        // find({ field: value })
        List<Document> find(String field, Object value) {
            return store.values().stream()
                .filter(d -> value.equals(d.get(field))).toList();
        }

        // Aggregation: group by a field and count
        Map<Object, Long> aggregate(String groupField) {
            return store.values().stream()
                .collect(Collectors.groupingBy(
                    d -> d.get(groupField) != null ? d.get(groupField) : "null",
                    Collectors.counting()));
        }

        int count() { return store.size(); }
    }

    public static void main(String[] args) {
        System.out.println("=== Lesson 5.3: NoSQL (MongoDB) ===\n");

        Collection users = new Collection();
        // insertOne()
        users.insertOne(new Document("u1").put("name","Alice").put("role","admin").put("score",95));
        users.insertOne(new Document("u2").put("name","Bob")  .put("role","user") .put("score",72));
        users.insertOne(new Document("u3").put("name","Carol").put("role","admin").put("score",88));
        users.insertOne(new Document("u4").put("name","Dave") .put("role","user") .put("score",60));

        System.out.println("--- findById ---");
        users.findById("u2").ifPresent(System.out::println);

        System.out.println("\n--- find({ role: 'admin' }) ---");
        users.find("role", "admin").forEach(System.out::println);

        System.out.println("\n--- aggregate({ $group: { _id: '$role', count: 1 } }) ---");
        users.aggregate("role").forEach((k, v) ->
            System.out.printf("  role=%-8s count=%d%n", k, v));

        System.out.println("\n--- MongoDB vs SQL guide ---");
        System.out.println("  Use MongoDB when:");
        System.out.println("    - Schema evolves frequently");
        System.out.println("    - Data is naturally hierarchical (embedded documents)");
        System.out.println("    - Horizontal scale-out is a primary requirement");
        System.out.println("  Use PostgreSQL when:");
        System.out.println("    - Strong ACID transactions are required");
        System.out.println("    - Complex multi-table joins are necessary");
        System.out.println("    - Relational integrity (FK, unique constraints) is critical");
    }
}